### PR TITLE
fix: fail early if there is no tmp dir specified

### LINKED ISSUE #176: Windows Temp file not working electron
## Operating System
- [ ] Linux
- [ ] Windows 7
- [x] Windows 10
- [ ] MacOS
- other: 

## NodeJS Version
- [ ] 0.x
- [ ] 4.x
- [ ] 6.x
- [ ] 7.x
- other: 8.6

## Tmp Version
TBD:Enter tmp version here
newest

## Expected Behavior
TBD:What have you expected tmp to do?
correct temp file.

## Experienced Behavior
TBD:What did actually happen?

It generates this file:
```javascript
let fileName = tmp.tmpNameSync();
```
```
undefined\temp\tmp-3476obo4mLnOL8Bp
```

Then i trying to write to this file:
```javascript
fs.writeFileSync(fileName, new Buffer(result.data));
```
```
no such file or directory, open 'C:\Users\xxx\xx\app-1.0.2\undefined\temp\tmp-3476obo4mLnOL8Bp'
```

### PR DESCRIPTION
**Pull request by silkentrance**
Fixes #176.

This will cause `_generateTmpName` to fail early if both `opts.dir` and `tmpDir` are undefined.

### CODE REVIEW

**Comment by silkentrance** [comment]
Still working on tests for this...

File: lib/tmp.js [hunk 1]
```diff
@@ -121,6 +121,11 @@ function _parseArguments(options, callback) {
  * @private
  */
 function _generateTmpName(opts) {
+
+  // fail early on missing tmp dir
+  if (!opts.dir && !tmpDir)
+    throw new Error("no tmp dir specified");
```
Comment (raszi) [inline lib/tmp.js]: Please use single-quotes in strings.

File: lib/tmp.js [hunk 2]
```diff
@@ -121,6 +121,11 @@ function _parseArguments(options, callback) {
  * @private
  */
 function _generateTmpName(opts) {
+
+  // fail early on missing tmp dir
+  if (!opts.dir && !tmpDir)
```
Comment (raszi) [inline lib/tmp.js]: Either put parenthesis around the branch or join them into one line.

File: lib/tmp.js (hunk 1 above)
Comment (raszi) [reply lib/tmp.js]: Please start the error with a capital letter.

**Comment by silkentrance** [comment]
@raszi thank you for the review. I will try to address these issues ASAP.

File: lib/tmp.js (hunk 1 above)
Comment (silkentrance) [reply lib/tmp.js]: done

File: lib/tmp.js (hunk 2 above)
Comment (silkentrance) [reply lib/tmp.js]: done

**Comment by silkentrance** [comment]
> Please also add tests.

Missing tests have been added.

**Comment by silkentrance** [comment]
@raszi tests have been added.

**Comment by silkentrance** [comment]
Merging now as all change requests have been met.
