### PR TITLE
fix #268: Revert "fix #246: remove any double quotes or single quotes…

### LINKED ISSUE #246: tmpNameSync: Bad result if the TMP/TEMP env. variables are enclosed in quotes
## Operating System
- [ ] Linux
- [ ] Windows 7
- [ x] Windows 10
- [ ] MacOS
- other: 

## NodeJS Version
- [ ] 0.x
- [ ] 4.x
- [ ] 6.x
- [ ] 7.x
- other: 10.16.2

## Tmp Version
TBD:0.1.0

## Expected Behavior
TBD: What have you expected tmp to do?

Create proper tmp-name without quotes

## Experienced Behavior
TBD: What did actually happen?

Created path names with embedded quotes if the env. vars TMP and TEMP has spaces in it. I have a space in my user name and we have to use our own TMP directories rather than using the system ones. To reproduce the problem in a shell/cmd set the TMP/TEMP variables to any path with spaces in it

  set TMP="C:\users\xxx\T M P"
  set TEMP="C:\users\xxx\T M P"
  node test.js

The above commands creates the following output. Yes, I can filter the path-name but it was unexpected
```
Created temporary filename:  "C:\Users\hdm\T M P"\tmp-4832vNUYEwQFRehF
```

And my test.js looks like
```JavaScript
var tmp = require('tmp');
var options = {};
var tmpname = tmp.tmpNameSync(options);
console.log('Created temporary filename: ', tmpname);
```

### LINKED ISSUE #268: Why does tmp remove quotes from paths ?
## Operating System
- [x] Linux
- [x] Windows 7
- [x] Windows 10
- [x] MacOS
- other: 

## NodeJS Version
- [x] 0.x
- [x] 4.x
- [x] 6.x
- [x] 7.x
- other: 

## Tmp Version
0.2.1

## Expected Behavior
Don't remove quotes from paths

## Experienced Behavior
Quotes are being removed

See https://github.com/raszi/node-tmp/blob/master/lib/tmp.js#L564-L575

For example on Windows the tmpdir is in general in `C:\Users\username\AppData\Local\Temp`. A username may contain a quote and / or a double quote (`Bob's Computer` for example).

`_getTmpName` calls `_sanitizeName` on `os.tmpdir()` and returns a folder that does not exist.

### PR DESCRIPTION
**Pull request by mbargiel**
… from os.tmpdir also sanitize dir option, the template option and the name option"

This reverts commit c8823e549280e11697a510184a69b63bf5bfef7a.

Single quotes must not be removed from paths because they are valid (even if hard to use)
on all OSes. Double quotes are only disallowed on Windows, but tmp should not change any
arg it gets; instead, it should rely on the underlying fs API to fail with an error
that the user needs to fix.

### CODE REVIEW

**Comment by mbargiel** [comment]
I successfully verified in my project that reverting this commit fixes the regression introduced when we upgraded from 0.1.0 to 0.2.1.

**Comment by silkentrance** [comment]
Thank you for the PR.

I will review the changes and then merge as this is a long standing issue.
I think I went overboard when sanitizing the name that way.

I am still wondering, though, why no CI checks have been executed.

File: test/name-sync-test.js [hunk 1]
```diff
@@ -53,35 +50,6 @@ describe('tmp', function () {
           }
         });
       });
-      describe('on issue #246', function () {
```
Comment (silkentrance) [inline test/name-sync-test.js:56]: Could you leave these tests and make these so that they check for the presence of the single quotes and double quotes instead?

File: test/name-test.js [hunk 2]
```diff
@@ -63,39 +62,6 @@ describe('tmp', function () {
           });
         });
       });
-      describe('on issue #246', function () {
```
Comment (silkentrance) [inline test/name-test.js:66]: Same here, tests must stay in place, yet test for the presence of the quotes.

**Review by silkentrance — CHANGES_REQUESTED** [review]

**Comment by silkentrance** [comment]
@raszi Would you be so kind to enable github actions so that we can use that for the CI instead of appveyor and travis-ci?

**Comment by silkentrance** [comment]
@raszi Thank you.

I just looked into the cost for the github actions, I think that this is a no-go 😄

**Comment by raszi** [comment]
> Yet, Github Free includes 500GB and 2000 Minutes...

Yes, I believe it could work for this project, I am using that with other free projects.

**Comment by silkentrance** [comment]
@raszi I do not see the projects, yet.

File: test/name-sync-test.js (hunk 1 above)
Comment (mbargiel) [reply test/name-sync-test.js:56]: Absolutely! I wasn't sure which you would have preferred between simply reverting or keeping the tests but amended to serve as regression tests. I'll do this when I can, either tonight or tomorrow.

Comment (mbargiel) [reply test/name-sync-test.js:56]: Please see [a831713](https://github.com/raszi/node-tmp/pull/278/commits/a831713743a1e370ebcda62f0709fdda9c0dd9d6).

File: test/name-test.js (hunk 2 above)
Comment (mbargiel) [reply test/name-test.js:66]: Please see [a831713](https://github.com/raszi/node-tmp/pull/278/commits/a831713743a1e370ebcda62f0709fdda9c0dd9d6).

**Review by silkentrance — APPROVED** [review]
