### PR TITLE
Fix for #17

### LINKED ISSUE #17: Should `_rmdirRecursiveSync` be re-implemented using a loop?
See [#840(bower)](https://github.com/bower/bower/issues/840).

When there are a large number of directories to clean up, the current implementation seems to result in a "Maximum call stack size exceeded" exception.

### PR DESCRIPTION
**Pull request by silkentrance**
- fixes #17:unwound recursive calls into a simple loop

The only problem that remains is that of available memory if the user managed to create so many directories and subdirectories that we eat up the memory while pushing the strings unto the stack...

### CODE REVIEW

File: lib/tmp.js [hunk 1]
```diff
@@ -191,22 +191,30 @@ function _createTmpFile(options, callback) {
...
-    var stat = fs.lstatSync(file);
-
-    if (stat.isDirectory()) {
-      _rmdirRecursiveSync(file);
-    } else {
-      fs.unlinkSync(file);
+function _rmdirRecursiveSync(root) {
+  var dirs = [];
+  dirs.push(root);
+  while (dirs.length) {
```
Comment (raszi) [inline lib/tmp.js]: Why not a simple:

```javascript
var
  dirs = [],
  dir;
while(dir = dirs.pop) {
  // ...
}
```

File: lib/tmp.js [hunk 2]
```diff
@@ -191,22 +191,30 @@ function _createTmpFile(options, callback) {
...
-    var file = path.join(dir, files[i]);
-    // lstat so we don't recurse into symlinked directories.
-    var stat = fs.lstatSync(file);
-
-    if (stat.isDirectory()) {
-      _rmdirRecursiveSync(file);
-    } else {
-      fs.unlinkSync(file);
+function _rmdirRecursiveSync(root) {
+  var dirs = [];
```
Comment (raszi) [inline lib/tmp.js]: We can start with it, don't need to call push explicitly.

```javascript
var dirs = [root];
```

**Comment by silkentrance** [comment]
@raszi Did a rebase to master and fixed the issues you pointed out.
